options:
   branch:
     default: "develop"
     description: |
       branch indicates which installation you want to do. If you want a stable installation, change this option to "master". 
     type: string
   revision: 
     default: "HEAD"   
     description: get a specific revison from the openair-cn git repository. 
     type: string
   realm:
     default: "openair4G.eur"
     description: |
       Diameter realm of the MME. HSS and EPC have to have the same. NO empty value.
     type: string
   eth:
     default: "eth0"
     description: |
       This is usefull especially when you are in manual environment so you have your own machines. The default value is eth0. NO empty value.
     type: string
   maxenb:
     default: "10"
     description: Maximum number of eNB that can connect to MME. Max Value is 10.
     type: string
   maxue:
     default: "10"
     description: |
       For debug purpose, used to restrict the number of served UEs the MME can handle. Max Value is 50.
     type: string
   relative_capacity:
     default: "10"
     description: |
       Even though this parameter is not used by the MME for controlling the MME load balancing within a pool (at least for now), the parameter has to be forwarded to the eNB during association procedure. Values going from 0 to 255.
     type: string
   mme_statistic_timer:
     default: "10"
     description: |
       Displayed statistic (stdout) period. You can access the stdout: cat /srv/.out on the machine where EPC charm is deployed.
     type: string 
   emergency_attach_supported:
     default: "no"
     description: This will attach the unauthenticated UEs (not supported).
     type: string
   authenticated_imsi_supported:
     default: "no"
     description: TO DO
     type: string   
   verbosity:
     default: "none"
     description: sets the asn1 log level verbosity. Valid values are "none", "info", or "annoying"
     type: string
   gummei_tai_mcc:
     default: "208"
     description: TAI=MCC.MNC:TAC. MCC is the Mobile Country Code. Must be three digits.
     type: string 
   gummei_tai_mnc:
     default: "93"
     description: TAI=MCC.MNC:TAC. MNC is the Mobile Network Code. Must be two or three digits.
     type: string
   gummei_tai_tac:
     default: "1"
     description: TAI=MCC.MNC:TAC. TAC is the Tracking Area Code.
     type: string
   ipv4_list_start:
     default: "192.188.1.0/24"
     description: First IP address pool that will be assigned to UEs.
     type: string
   ipv4_list_end:
     default: "192.188.2.0/24"
     description: Second IPv4 address pool that will be assigned to UEs.
     type: string
   ipv6_list:
     default: "2014:02:26::0/120"
     description: First IPv6 addresse pool available to be assigned to UEs.
     type: string
   DEFAULT_DNS_IPV4_ADDRESS:
     default: "8.8.8.8"
     description: IPv4 address of primary default DNS that can be queried by UEs.
     type: string
   DEFAULT_DNS_SEC_IPV4_ADDRESS:
     default: "8.8.8.8"
     description: IPv4 address of secondary default DNS that can be queried by UEs.
     type: string






